
export default {
    READ_MINE: 'READ_MINE',
    READ_ALL: 'READ_ALL',
    UPDATE_MINE: 'UPDATE_MINE',
    UPDATE_ALL: 'UPDATE_ALL',
    REMOVE_ALL: 'REMOVE_ALL',
    REMOVE_MINE: 'REMOVE_MINE',
    CREATE_ALL: 'CREATE_ALL',
    CREATE_MINE: 'CREATE_MINE'
}