export const RECEIVE_FLEETS = 'RECEIVE_FLEETS'
export const RECEIVE_FLEET = 'RECEIVE_FLEET'
export const CREATE_FLEET ='CREATE_FLEET'
export const DELETE_FLEET = 'DELETE_FLEET'

export const RECEIVE_SUBFLEETS = 'RECEIVE_SUBFLEETS'
export const CREATE_SUBFLEET = 'CREATE_SUBFLEET'
export const CLEAR_SUBFLEETS = 'CLEAR_SUBFLEETS'
export const ADD_VEHICLE_TO_SUBFLEETS = 'ADD_VEHICLE_TO_SUBFLEETS'
export const REMOVE_VEHICLE_FROM_SUBFLEETS = 'REMOVE_VEHICLE_FROM_SUBFLEETS'

export const RECEIVE_CLIENTS = 'RECEIVE_CLIENT'

export const RECEIVE_VEHICLES = 'RECEIVE_VEHICLES'
export const RECEIVE_VEHICLE = 'RECEIVE_VEHICLE'
export const CREATE_VEHICLE = 'CREATE_VEHICLE'
export const DELETE_VEHICLE = 'DELETE_VEHICLE'
export const RECEIVE_VEHICLE_TYPES = 'RECEIVE_VEHICLE_TYPES'
export const RECEIVE_VEHICLE_TYPE = 'RECEIVE_VEHICLE_TYPE'